### PR TITLE
Fix lock wait timing calculation and reduce contention

### PR DESCRIPTION
**Pull request by deiwin**
Info in commits.

### CODE REVIEW

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/2//console)).

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/2//console)).

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/3//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-95/3//console)) to continue the deployment.

**Pull request merged**
