### PR TITLE
Include aws-iam-authenticator in deployer container

### PR DESCRIPTION
**Pull request by deiwin**
May be used by some k8s configurations.

### CODE REVIEW

**Comment by deiwin** [comment]
!deploy

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-52/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-52/3//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-52/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-52/3//console)).

**Comment by deiwin** [comment]
!deploy

**Pull request merged**
