### PR TITLE
Upgrade toolbox to have 3.8 helm installed

### PR DESCRIPTION
**Pull request by kuzaxak**
Image was built [here][1]. New helm is needed to support OCI charts storage natively.

[1]: https://github.com/salemove/jenkins-toolbox/pull/43

### CODE REVIEW

**Review by indrekj — APPROVED** [review]

**Comment by kuzaxak** [comment]
!deploy

**Comment by indrekj** [comment]
https://github.com/salemove/pipeline-lib/blob/master/src/com/salemove/helm/Deployment.groovy#L140 this can be removed as well I guess

**Comment by sm-deployer** [comment]
@kuzaxak, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-158/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-158/2//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
@kuzaxak, the changes have been deployed to beta. Please continue [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-158/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-158/2//console)).

**Comment by kuzaxak** [comment]
> https://github.com/salemove/pipeline-lib/blob/master/src/com/salemove/helm/Deployment.groovy#L140 this can be removed as well I guess

@indrekj yes

**Pull request merged**
