### PR TITLE
Enable checking for reviews

### PR DESCRIPTION
**Pull request by deiwin**

### CODE REVIEW

**Comment by deiwin** [comment]
!deploy

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/3//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/5/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/5//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/5/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-57/5//console)) to continue the deployment.

**Pull request merged**
