### PR TITLE
Update env/context names & quick rollback link

### PR DESCRIPTION
**Pull request by deiwin**
Info in commits.

### CODE REVIEW

**Comment by deiwin** [comment]
Starting `!deploy` for testing. Won't finish it until after review.

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-73/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-73/3//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-73/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-73/3//console)) to continue the deployment.

**Pull request merged**
