### PR TITLE
Reset merge commit author when deployignore used

### PR DESCRIPTION
**Pull request by laurglia**
When an outdated branch is deployed, a merge commit is created. At
first, this commit is created by `Jenkins <nobody@nowhere>`. Before
deploying, we set the author of this commit to `sm-deployer
<support@salemove.com>`.

However, until now, the author was changed only when a pull request was
deployed but not when it was directly merged because only files matching
deployignore were changed.

This is a problem for two reasons:
1. It is inconsistent.
2. It led to master build failing in some repositories (for more
details, see linked ticket).

This commit fixes that problem. Now the merge commit author is always
updated.

AUTO-363

### CODE REVIEW

**Comment by laurglia** [comment]
I will try to deploy both outdated branch and up-to-date branch.

**Comment by laurglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
@laurglia, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/2//console)).

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @laurglia, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/2//console)).

**Review by take-five — APPROVED** [review]

**Review by rrebane — APPROVED** [review]

**Comment by laurglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @laurglia, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/4/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/4//console)).

**Comment by laurglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
@laurglia, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/6/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/6//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @laurglia, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/6/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/6//console)).

**Comment by laurglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
@laurglia, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/9/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/9//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
@laurglia, the changes have been deployed to beta. Please continue [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/9/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-132/9//console)).

**Pull request merged**
