### PR TITLE
[WIP] Testing docker image reuse for deploys

### PR DESCRIPTION
**Pull request by deiwin**

### CODE REVIEW

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/3//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/4/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/4//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/5/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/5//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/8//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/9//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/11//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/12//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/16/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/16//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/21/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/21//console)).

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/21/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/21//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23//console)).

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-60/23//console)).

**Comment by deiwin** [comment]
Enough testing

**Pull request closed without merging**
