### PR TITLE
Test

### PR DESCRIPTION
**Pull request by laursisask**
Testing one thing from my personal account

### CODE REVIEW

**Comment by laursisask** [comment]
!deploy

**Comment by take-five** [comment]
Comment triggers do not work, I guess :)

**Comment by laursisask** [comment]
!deploy

**Comment by take-five** [comment]
Did it work?

**Comment by laurglia** [comment]
> Did it work?

It does run Jenkins pipeline. The Jenkinsfile cannot be changed (I assume it takes it from master like you thought) but tests and everything else can be changed and that code will be run in CI.

I tried sending the environment variable to a webhook and that worked OK. There wasn't anything too critical in the environment variables. I'm currently doing some additional tests under https://github.com/salemove/pipeline-lib/pull/162 to see if the job can access data from other builds and modify them. Will create a ticket once I'm more certain what the exact impact here is.

**Comment by take-five** [comment]
Can you disable tests for now then?

**Pull request closed without merging**
