### PR TITLE
Increase memory limit of deploy test pod

### PR DESCRIPTION
**Pull request by deiwin**
A new version of runc [doesn't work well][1] with very small memory limits.

[1]: https://github.com/opencontainers/runc/issues/1980#issuecomment-463148112

### CODE REVIEW

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @deiwin, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-79/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-79/3//console)).

**Comment by deiwin** [comment]
!deploy

**Comment by sm-deployer** [comment]
@deiwin, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-79/4/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-79/4//console)) to continue the deployment.

**Comment by deiwin** [comment]
I increased it further to 30, because I thought 20 wasn't enough. While actually 20 worked just fine, it's just that the rollback to the low limit failed in acceptance. This time I manually forced the rollout to pass and deploy works well.

**Pull request merged**
