### PR TITLE
Test changes in release

### PR DESCRIPTION
**Pull request by aronglia**

### CODE REVIEW

**Comment by aronglia** [comment]
!deploy

**Comment by aronglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
@aronglia, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/2//console)).

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @aronglia, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/2/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/2//console)).

**Comment by aronglia** [comment]
!deploy

**Comment by sm-deployer** [comment]
@aronglia, your input is required [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3//console)).

**Comment by sm-deployer** [comment]
@aronglia, the changes were validated in acceptance. Please click **Proceed** [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3//console)) to continue the deployment.

**Comment by sm-deployer** [comment]
Deploy failed or was aborted. @aronglia, please check the logs [here](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3/display/redirect) (or [in the old UI](https://ci.at.samo.io/job/salemove/job/pipeline-lib/job/PR-112/3//console)).

**Pull request closed without merging**
